Fixes Yum OpenShift Repo Priority
Recently, new OpenShift packages have landed in the fedora repo
and are taking priority over the openshift repo packages.  This is
causing Puppet to fail with the following errors:

Error: /Stage[main]/Openshift_origin::Broker/Package
[openshift-origin-broker-util]/ensure: change from absent to
present failed: Execution of '/bin/yum -d 0 -e 0 -y
install openshift-origin-broker-util' returned 1:

This patch adds priority to the packages in the origin-base and
origin-dep repos.