Adds NetworkManager Package and Service Dependency
Previously, the puppet agent installation was failing due to the
NetworkManager-Wait-online service not being enabled:

Error: Could not enable NetworkManager-wait-online: Execution of
'/sbin/chkconfig NetworkManager-wait-online on' returned 1: error
reading information on service NetworkManager-wait-online:
No such file or directory

This patch adds the required NetworkManager package and dependency
for the NetworkManager-wait-online service.